services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
        - postgres:/data/postgres
    ports:
        - 5435:5432
    networks:
        - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  pgadmin:
    container_name: pgadmin-bsn
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 7070:80
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local
